# coding: utf-8

"""
Single source of truth for the AZH signal mass grid.

WHY THIS FILE EXISTS
--------------------
The 262 signal mass points were previously written out by hand inside the
``process_names`` list in ``azh/config/config_run3.py``. That is fine for one
consumer, but the inference models need the same list at *module import time*
(see ``azh/inference/default.py``), long before any config exists. Duplicating
the list in two places guarantees they drift.

So the grid lives here as (mA, mH) pairs, and both consumers derive from it:

  * ``config_run3.py``  -> ``process_names += list(AZH_SIGNAL_PROCESSES)``
  * ``azh/inference/default.py`` -> one derived inference model per point

Storing masses rather than name strings is deliberate: the elliptical binning
of AN-2022/158 Sec. 7 is constructed per mass hypothesis, so downstream code
will need (mA, mH) as numbers, not just as a name to be re-parsed.

The grid is generated by the AZH signal request; if new points are produced,
add them to ``MASS_GRID`` here and nowhere else.
"""

# mA -> list of mH values, in GeV. 262 points total.
MASS_GRID: dict[int, list[int]] = {
    430: [330],
    450: [330, 350],
    500: [330, 350, 370, 400],
    550: [330, 350, 400, 450],
    600: [330, 350, 400, 450, 500],
    650: [330, 350, 400, 450, 500, 550],
    700: [330, 350, 370, 400, 450, 500, 550],
    750: [330, 350, 400, 450, 500, 550, 600, 650],
    800: [330, 350, 400, 450, 500, 550, 600, 650, 700],
    850: [330, 350, 400, 450, 500, 550, 600, 650, 700, 750],
    900: [330, 350, 370, 400, 450, 500, 550, 600, 650, 700, 750, 800],
    950: [330, 350, 400, 450, 500, 550, 600, 650, 700, 750, 800, 850],
    1000: [330, 350, 400, 450, 500, 550, 600, 650, 700, 750, 800, 850, 900],
    1050: [330, 350, 400, 450, 500, 550, 600, 700, 750, 800, 850, 900, 950],
    1100: [
        330, 350, 400, 450, 500, 550, 600, 650, 700, 750, 800, 850, 900,
        950, 1000
    ],
    1150: [330, 350, 450, 550, 650, 750, 850, 950, 1050],
    1200: [330, 350, 400, 500, 600, 700, 800, 850, 900, 1000, 1100],
    1300: [350, 400, 500, 600, 700, 800, 900, 1000, 1100, 1200],
    1400: [350, 400, 500, 600, 700, 800, 900, 1000, 1100, 1200, 1300],
    1500: [350, 400, 500, 600, 700, 900, 1000, 1100, 1200, 1300, 1400],
    1600: [350, 400, 500, 600, 900, 1000, 1100, 1200, 1300, 1400, 1500],
    1700: [
        350, 400, 500, 600, 700, 800, 900, 1000, 1100, 1200, 1300, 1400,
        1500, 1600
    ],
    1800: [
        350, 400, 500, 600, 700, 800, 900, 1000, 1100, 1200, 1300, 1400,
        1500, 1600, 1700
    ],
    1900: [
        350, 400, 500, 600, 700, 800, 900, 1000, 1100, 1200, 1300, 1400,
        1500, 1600, 1700, 1800
    ],
    2000: [
        350, 400, 500, 600, 700, 800, 900, 1000, 1100, 1200, 1300, 1400,
        1600, 1700, 1800, 1900
    ],
    2100: [
        350, 400, 500, 600, 700, 800, 900, 1000, 1100, 1200, 1300, 1400,
        1500, 1700, 1800, 1900, 2000
    ],
}


def process_name(m_a: int, m_h: int) -> str:
    """
    Build the cmsdb process name for one mass point.

    This spelling is load-bearing: it has to match the process registered in
    cmsdb and the dataset key used in the config, so it lives in exactly one
    place.
    """
    return f"azh_htt_zll_a{m_a}_h{m_h}"


# Generator suffix on the cmsdb dataset names. The processes are named
# `azh_htt_zll_a<mA>_h<mH>` but the datasets carry the generator, e.g.
# `azh_htt_zll_a1000_h330_amcatnlo`. Kept as a constant because it is the kind
# of thing that changes when samples are reproduced.
AZH_DATASET_SUFFIX = "_amcatnlo"


def dataset_name(m_a: int, m_h: int) -> str:
    """cmsdb dataset name for one mass point (process name + generator suffix)."""
    return f"{process_name(m_a, m_h)}{AZH_DATASET_SUFFIX}"


def masses(name: str) -> tuple[int, int]:
    """
    Inverse of :py:func:`process_name`: recover (mA, mH) from a process name.

    Raises ValueError rather than returning None, so a typo in a derived
    inference model name fails immediately instead of silently producing a
    model for the wrong hypothesis.
    """
    prefix = "azh_htt_zll_a"
    if not name.startswith(prefix) or "_h" not in name:
        raise ValueError(f"'{name}' is not an AZH signal process name")
    # tolerate a dataset name being passed in
    if name.endswith(AZH_DATASET_SUFFIX):
        name = name[: -len(AZH_DATASET_SUFFIX)]
    a_str, _, h_str = name[len(prefix):].partition("_h")
    return int(a_str), int(h_str)


# Flat, ordered tuple of all signal process names. Ordered by (mA, mH) so that
# anything iterating it -- derived model creation, submission loops, limit
# scans -- produces a reproducible order.
AZH_SIGNAL_PROCESSES: tuple[str, ...] = tuple(
    process_name(m_a, m_h)
    for m_a in sorted(MASS_GRID)
    for m_h in sorted(MASS_GRID[m_a])
)


# Flat, ordered tuple of all signal DATASET names, in the same order as
# AZH_SIGNAL_PROCESSES so the two zip together.
AZH_SIGNAL_DATASETS: tuple[str, ...] = tuple(
    dataset_name(m_a, m_h)
    for m_a in sorted(MASS_GRID)
    for m_h in sorted(MASS_GRID[m_a])
)